# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bc8d2dcb74a0776f3f596e1631559adf08b1baa72afd9bc93c3c2bcd7f642cdfd37f5da82bf5f7341ec937eaad75979c1aba312e70a766902bec11a2540769a

test:
  secret_key_base: 9bcc382c968c5fdf94ffdebcedeab9549f604842aeae1ccc9ce939dc6bbd15b73d1ea084476ec671a86560d82c10f075f00b0e912e7cb6def193d119ce6ca101

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
